# Offline Runtime Settings
app_name: MAITRI_AI_Assistant
version: 1.0.0
debug_mode: true
log_level: INFO

# Data paths
log_directory: data/logs/
model_directory: data/models/
response_library_path: modules/conversation/response_library.json

# Hardware settings (for input_manager)
camera_index: 0
mic_device_index: 1
sample_rate: 16000 # Audio sample rate

# Reporting settings
report_format: json # Can be json, pdf (requires external library)
sync_on_startup: true
