# Emotion Detection Sensitivity Thresholds
# These values determine when an emotion is considered 'significant' for logging or response generation.

# Minimum confidence score (0.0 to 1.0) for an emotion to be registered
min_confidence: 0.70

# Duration (in seconds) an intense negative emotion must persist before triggering a stress flag
negative_emotion_persistence_s: 15

# Threshold for 'Neutral' classification confidence before deferring to the multimodal fusion
neutral_deferral_threshold: 0.95

# Custom thresholds for specific negative emotions
emotion_specific:
  anger: 0.85
  sadness: 0.80
  fear: 0.75
  distress: 0.90

# Health monitoring thresholds
stress_level_high: 0.75
fatigue_mean_threshold: 0.65

# Add to thresholds.yaml:
fusion_high_confidence: 0.8
fusion_weights:
  facial: 0.6
  speech: 0.4