# Training Configuration for MAITRI AI Assistant Models

# Facial Emotion Model Configuration
facial_emotion:
  model_type: 'cnn'  # Options: 'cnn', 'resnet', 'mobilenet'
  num_classes: 7
  img_size: 48
  
  training:
    epochs: 50
    batch_size: 64
    learning_rate: 0.001
    weight_decay: 0.0001
    optimizer: 'adam'
    
  augmentation:
    enabled: true
    rotation: 10
    horizontal_flip: true
    brightness: 0.2
    contrast: 0.2
  
  dataset:
    name: 'fer2013'
    train_split: 0.8
    val_split: 0.1
    test_split: 0.1

# Speech Emotion Model Configuration
speech_emotion:
  model_type: 'lstm'  # Options: 'lstm', 'cnn', 'cnn_lstm', 'attention'
  num_classes: 8
  input_size: 40  # MFCC coefficients
  seq_length: 100
  hidden_size: 128
  num_layers: 2
  
  training:
    epochs: 100
    batch_size: 32
    learning_rate: 0.0001
    weight_decay: 0.0001
    optimizer: 'adam'
  
  audio:
    sample_rate: 16000
    n_mfcc: 40
    max_duration: 3.0  # seconds
    
  augmentation:
    enabled: true
    noise: true
    pitch_shift: true
    time_stretch: true
  
  dataset:
    name: 'ravdess'  # Options: 'ravdess', 'crema_d', 'tess'
    train_split: 0.8
    val_split: 0.1
    test_split: 0.1

# Multimodal Fusion Configuration
multimodal_fusion:
  fusion_type: 'late'  # Options: 'late', 'early', 'attention', 'confidence'
  num_classes: 7
  
  training:
    epochs: 30
    batch_size: 32
    learning_rate: 0.0001
    fine_tune: true

# Hardware Configuration
hardware:
  device: 'cuda'  # 'cuda' or 'cpu'
  num_workers: 4
  pin_memory: true
  
# Paths
paths:
  data_dir: 'datasets'
  checkpoint_dir: 'checkpoints'
  model_output_dir: '../data/models'
  log_dir: 'logs'

# Emotion Labels
emotion_labels:
  facial:
    - 'Angry'
    - 'Disgust'
    - 'Fear'
    - 'Happy'
    - 'Sad'
    - 'Surprise'
    - 'Neutral'
  
  speech:
    - 'neutral'
    - 'calm'
    - 'happy'
    - 'sad'
    - 'angry'
    - 'fearful'
    - 'disgust'
    - 'surprised'
